"""records signature seal governance

Revision ID: a3d91f6a7b75
Revises: z2c80e5f6a64
Create Date: 2026-08-15 04:31:20.267377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d91f6a7b75'
down_revision: Union[str, None] = 'z2c80e5f6a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Historical local/test simulations were stored as legally signed despite
    # live_verified=false. Preserve the evidence but correct the business truth
    # before enforcing the invariant.
    op.execute(
        "UPDATE lease_contract_documents "
        "SET status = 'SANDBOX_COMPLETED' "
        "WHERE status = 'SIGNED' AND live_verified = false"
    )
    with op.batch_alter_table('lease_contract_documents', schema=None) as batch_op:
        batch_op.create_check_constraint(
            'ck_lease_document_signed_truth',
            "status <> 'SIGNED' OR live_verified",
        )

    op.create_table('signature_providers',
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('adapter_kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('credential_ref', sa.String(length=128), nullable=True),
    sa.Column('health_json', sa.JSON(), nullable=False),
    sa.Column('live_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('lock_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('NOT_CONNECTED','SANDBOX','CONNECTED','DEGRADED')", name='ck_signature_provider_status'),
    sa.CheckConstraint("(status = 'CONNECTED' AND live_verified) OR (status <> 'CONNECTED' AND NOT live_verified)", name='ck_signature_provider_truth'),
    sa.CheckConstraint('lock_version > 0', name='ck_signature_provider_lock'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uk_signature_provider_code'),
    sa.UniqueConstraint('tenant_id', 'id', name='uk_signature_provider_tenant_id')
    )
    op.create_table('record_categories',
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('retention_mode', sa.String(length=16), nullable=False),
    sa.Column('retention_years', sa.Integer(), nullable=True),
    sa.Column('confidentiality_max', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('lock_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("(retention_mode = 'PERMANENT' AND retention_years IS NULL) OR (retention_mode = 'YEARS' AND retention_years > 0)", name='ck_record_category_years'),
    sa.CheckConstraint("confidentiality_max IN ('PUBLIC','INTERNAL','CONFIDENTIAL','RESTRICTED')", name='ck_record_category_confidentiality'),
    sa.CheckConstraint("retention_mode IN ('YEARS','PERMANENT')", name='ck_record_category_retention'),
    sa.CheckConstraint("status IN ('ACTIVE','RETIRED')", name='ck_record_category_status'),
    sa.CheckConstraint('lock_version > 0', name='ck_record_category_lock'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uk_record_category_code'),
    sa.UniqueConstraint('tenant_id', 'id', name='uk_record_category_tenant_id')
    )
    op.create_table('seal_assets',
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('park_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('seal_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('custodian_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('lock_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("kind IN ('OFFICIAL','CONTRACT','FINANCE','LEGAL_REPRESENTATIVE','ELECTRONIC','OTHER')", name='ck_seal_asset_kind'),
    sa.CheckConstraint("status IN ('ACTIVE','TRANSFER_PENDING','SUSPENDED','LOST','RETIRED')", name='ck_seal_asset_status'),
    sa.CheckConstraint('lock_version > 0', name='ck_seal_asset_lock'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['custodian_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'park_id'], ['parks.tenant_id', 'parks.id'], name='fk_seal_asset_park'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uk_seal_asset_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'seal_code', name='uk_seal_asset_code')
    )
    with op.batch_alter_table('seal_assets', schema=None) as batch_op:
        batch_op.create_index('ix_seal_asset_catalog', ['tenant_id', 'park_id', 'status', 'kind'], unique=False)

    op.create_table('record_files',
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('park_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('record_no', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidentiality', sa.String(length=16), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retention_mode', sa.String(length=16), nullable=False),
    sa.Column('retention_years', sa.Integer(), nullable=True),
    sa.Column('retention_until', sa.Date(), nullable=True),
    sa.Column('filed_at', sa.DateTime(), nullable=True),
    sa.Column('filed_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('disposed_at', sa.DateTime(), nullable=True),
    sa.Column('disposed_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('lock_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("confidentiality IN ('PUBLIC','INTERNAL','CONFIDENTIAL','RESTRICTED')", name='ck_record_file_confidentiality'),
    sa.CheckConstraint("retention_mode IN ('YEARS','PERMANENT')", name='ck_record_file_retention'),
    sa.CheckConstraint("(retention_mode = 'PERMANENT' AND retention_years IS NULL AND retention_until IS NULL) OR (retention_mode = 'YEARS' AND retention_years > 0 AND retention_until IS NOT NULL)", name='ck_record_file_retention_value'),
    sa.CheckConstraint("status IN ('DRAFT','FILED','ON_HOLD','DISPOSITION_PENDING','DISPOSED')", name='ck_record_file_status'),
    sa.CheckConstraint('lock_version > 0', name='ck_record_file_lock'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['disposed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['filed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'category_id'], ['record_categories.tenant_id', 'record_categories.id'], name='fk_record_file_category'),
    sa.ForeignKeyConstraint(['tenant_id', 'park_id'], ['parks.tenant_id', 'parks.id'], name='fk_record_file_park'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uk_record_file_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'record_no', name='uk_record_file_no')
    )
    with op.batch_alter_table('record_files', schema=None) as batch_op:
        batch_op.create_index('ix_record_file_catalog', ['tenant_id', 'park_id', 'status', 'category_id'], unique=False)
        batch_op.create_index('ix_record_file_retention', ['tenant_id', 'retention_until', 'status'], unique=False)

    op.create_table('seal_custody_events',
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('park_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('seal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('from_custodian_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('to_custodian_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('actor_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.CheckConstraint("event_type IN ('CREATED','TRANSFER_REQUESTED','TRANSFER_ACCEPTED','SUSPENDED','LOST','RECOVERED','RETIRED')", name='ck_seal_custody_event_type'),
    sa.CheckConstraint("status IN ('PENDING','COMPLETED','CANCELLED')", name='ck_seal_custody_event_status'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_custodian_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'seal_id'], ['seal_assets.tenant_id', 'seal_assets.id'], name='fk_seal_custody_event_seal'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['to_custodian_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seal_custody_events', schema=None) as batch_op:
        batch_op.create_index('ix_seal_custody_timeline', ['tenant_id', 'seal_id', 'occurred_at'], unique=False)
        batch_op.create_index('uk_seal_pending_transfer', ['tenant_id', 'seal_id'], unique=True, postgresql_where=sa.text("event_type = 'TRANSFER_REQUESTED' AND status = 'PENDING'"), sqlite_where=sa.text("event_type = 'TRANSFER_REQUESTED' AND status = 'PENDING'"))

    op.create_table('record_holds',
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('park_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('record_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('placed_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.Column('released_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('release_reason', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','RELEASED')", name='ck_record_hold_status'),
    sa.ForeignKeyConstraint(['placed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['released_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'record_id'], ['record_files.tenant_id', 'record_files.id'], name='fk_record_hold_record'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('record_holds', schema=None) as batch_op:
        batch_op.create_index('uk_record_hold_active', ['tenant_id', 'record_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))

    op.create_table('record_revisions',
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('park_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('record_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('attachment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('supersedes_revision_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE','DISPOSED')", name='ck_record_revision_status'),
    sa.CheckConstraint('size_bytes > 0', name='ck_record_revision_size'),
    sa.CheckConstraint('version_no > 0', name='ck_record_revision_version'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'attachment_id'], ['attachments.tenant_id', 'attachments.id'], name='fk_record_revision_attachment'),
    sa.ForeignKeyConstraint(['tenant_id', 'record_id'], ['record_files.tenant_id', 'record_files.id'], name='fk_record_revision_record'),
    sa.ForeignKeyConstraint(['tenant_id', 'supersedes_revision_id'], ['record_revisions.tenant_id', 'record_revisions.id'], name='fk_record_revision_supersedes'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uk_record_revision_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'record_id', 'version_no', name='uk_record_revision_version')
    )
    with op.batch_alter_table('record_revisions', schema=None) as batch_op:
        batch_op.create_index('ix_record_revision_record', ['tenant_id', 'record_id', 'version_no'], unique=False)

    op.create_table('record_access_requests',
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('park_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('record_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('purpose', sa.String(length=1000), nullable=False),
    sa.Column('requested_until', sa.DateTime(), nullable=False),
    sa.Column('requester_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('approval_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('request_key', sa.String(length=128), nullable=False),
    sa.Column('lock_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("mode IN ('VIEW','BORROW')", name='ck_record_access_mode'),
    sa.CheckConstraint("status IN ('PENDING_APPROVAL','APPROVED','APPROVAL_RETURNED','REJECTED','CHECKED_OUT','RETURNED','EXPIRED','WITHDRAWN')", name='ck_record_access_status'),
    sa.CheckConstraint('lock_version > 0', name='ck_record_access_lock'),
    sa.ForeignKeyConstraint(['approval_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'record_id'], ['record_files.tenant_id', 'record_files.id'], name='fk_record_access_record'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'request_key', name='uk_record_access_key')
    )
    with op.batch_alter_table('record_access_requests', schema=None) as batch_op:
        batch_op.create_index('ix_record_access_queue', ['tenant_id', 'park_id', 'status', 'requested_until'], unique=False)

    op.create_table('record_dispositions',
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('park_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('record_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('requested_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('approval_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('request_key', sa.String(length=128), nullable=False),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=True),
    sa.Column('storage_deletion_status', sa.String(length=32), nullable=False),
    sa.Column('disposed_at', sa.DateTime(), nullable=True),
    sa.Column('lock_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('PENDING_APPROVAL','APPROVED','APPROVAL_RETURNED','CONFIRMING','DISPOSED','REJECTED','WITHDRAWN')", name='ck_record_disposition_status'),
    sa.CheckConstraint('lock_version > 0', name='ck_record_disposition_lock'),
    sa.ForeignKeyConstraint(['approval_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'record_id'], ['record_files.tenant_id', 'record_files.id'], name='fk_record_disposition_record'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'request_key', name='uk_record_disposition_key'),
    sa.UniqueConstraint('tenant_id', 'id', name='uk_record_disposition_tenant_id')
    )
    with op.batch_alter_table('record_dispositions', schema=None) as batch_op:
        batch_op.create_index('uk_record_disposition_open', ['tenant_id', 'record_id'], unique=True, postgresql_where=sa.text("status IN ('PENDING_APPROVAL','APPROVED','CONFIRMING')"), sqlite_where=sa.text("status IN ('PENDING_APPROVAL','APPROVED','CONFIRMING')"))

    op.create_table('record_integrity_events',
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('park_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('record_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('revision_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('expected_checksum', sa.String(length=64), nullable=False),
    sa.Column('actual_checksum', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('verified_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.CheckConstraint("result IN ('MATCH','MISMATCH','UNAVAILABLE')", name='ck_record_integrity_result'),
    sa.ForeignKeyConstraint(['tenant_id', 'record_id'], ['record_files.tenant_id', 'record_files.id'], name='fk_record_integrity_record'),
    sa.ForeignKeyConstraint(['tenant_id', 'revision_id'], ['record_revisions.tenant_id', 'record_revisions.id'], name='fk_record_integrity_revision'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uk_record_integrity_key')
    )
    with op.batch_alter_table('record_integrity_events', schema=None) as batch_op:
        batch_op.create_index('ix_record_integrity_timeline', ['tenant_id', 'record_id', 'verified_at'], unique=False)

    op.create_table('seal_use_applications',
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('park_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('seal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('record_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('revision_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('revision_checksum', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=1000), nullable=False),
    sa.Column('copy_count', sa.Integer(), nullable=False),
    sa.Column('requested_for', sa.DateTime(), nullable=False),
    sa.Column('applicant_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('approval_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('application_key', sa.String(length=128), nullable=False),
    sa.Column('lock_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('PENDING_APPROVAL','APPROVED','APPROVAL_RETURNED','EXECUTED','REJECTED','WITHDRAWN','CANCELLED')", name='ck_seal_use_status'),
    sa.CheckConstraint('copy_count > 0', name='ck_seal_use_copy_count'),
    sa.CheckConstraint('lock_version > 0', name='ck_seal_use_lock'),
    sa.ForeignKeyConstraint(['applicant_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['approval_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'record_id'], ['record_files.tenant_id', 'record_files.id'], name='fk_seal_use_record'),
    sa.ForeignKeyConstraint(['tenant_id', 'revision_id'], ['record_revisions.tenant_id', 'record_revisions.id'], name='fk_seal_use_revision'),
    sa.ForeignKeyConstraint(['tenant_id', 'seal_id'], ['seal_assets.tenant_id', 'seal_assets.id'], name='fk_seal_use_seal'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'application_key', name='uk_seal_use_key'),
    sa.UniqueConstraint('tenant_id', 'id', name='uk_seal_use_tenant_id')
    )
    with op.batch_alter_table('seal_use_applications', schema=None) as batch_op:
        batch_op.create_index('ix_seal_use_queue', ['tenant_id', 'park_id', 'status', 'requested_for'], unique=False)

    op.create_table('signature_envelopes',
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('park_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('provider_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('record_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('revision_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('revision_checksum', sa.String(length=64), nullable=False),
    sa.Column('envelope_no', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider_ref', sa.String(length=128), nullable=True),
    sa.Column('live_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('lock_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('DRAFT','PENDING','SANDBOX_COMPLETED','COMPLETED','DECLINED','VOID','FAILED')", name='ck_signature_envelope_status'),
    sa.CheckConstraint("(status = 'COMPLETED' AND live_verified) OR (status <> 'COMPLETED' AND NOT live_verified)", name='ck_signature_envelope_truth'),
    sa.CheckConstraint('lock_version > 0', name='ck_signature_envelope_lock'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'provider_id'], ['signature_providers.tenant_id', 'signature_providers.id'], name='fk_signature_envelope_provider'),
    sa.ForeignKeyConstraint(['tenant_id', 'record_id'], ['record_files.tenant_id', 'record_files.id'], name='fk_signature_envelope_record'),
    sa.ForeignKeyConstraint(['tenant_id', 'revision_id'], ['record_revisions.tenant_id', 'record_revisions.id'], name='fk_signature_envelope_revision'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'envelope_no', name='uk_signature_envelope_no'),
    sa.UniqueConstraint('tenant_id', 'id', name='uk_signature_envelope_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'provider_id', 'provider_ref', name='uk_signature_provider_ref'),
    sa.UniqueConstraint('tenant_id', 'source_type', 'source_id', 'revision_id', name='uk_signature_source_revision')
    )
    with op.batch_alter_table('signature_envelopes', schema=None) as batch_op:
        batch_op.create_index('ix_signature_envelope_queue', ['tenant_id', 'park_id', 'status', 'created_at'], unique=False)

    op.create_table('record_disposition_confirmations',
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('disposition_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('confirmer_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['confirmer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'disposition_id'], ['record_dispositions.tenant_id', 'record_dispositions.id'], name='fk_disposition_confirmation'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'disposition_id', 'confirmer_user_id', name='uk_disposition_confirmer')
    )
    op.create_table('seal_use_receipts',
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('park_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('application_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('revision_checksum', sa.String(length=64), nullable=False),
    sa.Column('copy_count', sa.Integer(), nullable=False),
    sa.Column('executor_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('evidence_attachment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['executor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'application_id'], ['seal_use_applications.tenant_id', 'seal_use_applications.id'], name='fk_seal_use_receipt_application'),
    sa.ForeignKeyConstraint(['tenant_id', 'evidence_attachment_id'], ['attachments.tenant_id', 'attachments.id'], name='fk_seal_use_receipt_attachment'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'application_id', name='uk_seal_use_receipt_application'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uk_seal_use_receipt_key')
    )
    op.create_table('signature_events',
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('provider_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('envelope_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'envelope_id'], ['signature_envelopes.tenant_id', 'signature_envelopes.id'], name='fk_signature_event_envelope'),
    sa.ForeignKeyConstraint(['tenant_id', 'provider_id'], ['signature_providers.tenant_id', 'signature_providers.id'], name='fk_signature_event_provider'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider_id', 'source_event_id', name='uk_signature_event_source')
    )
    with op.batch_alter_table('signature_events', schema=None) as batch_op:
        batch_op.create_index('ix_signature_event_timeline', ['tenant_id', 'envelope_id', 'occurred_at'], unique=False)

    op.create_table('signature_participants',
    sa.Column('tenant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('envelope_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('contact_masked', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.CheckConstraint("role IN ('SIGNER','CC','APPROVER')", name='ck_signature_participant_role'),
    sa.CheckConstraint("status IN ('PENDING','COMPLETED','DECLINED')", name='ck_signature_participant_status'),
    sa.CheckConstraint('position > 0', name='ck_signature_participant_position'),
    sa.ForeignKeyConstraint(['tenant_id', 'envelope_id'], ['signature_envelopes.tenant_id', 'signature_envelopes.id'], name='fk_signature_participant_envelope'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'envelope_id', 'position', name='uk_signature_participant_position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signature_participants')
    with op.batch_alter_table('signature_events', schema=None) as batch_op:
        batch_op.drop_index('ix_signature_event_timeline')

    op.drop_table('signature_events')
    op.drop_table('seal_use_receipts')
    op.drop_table('record_disposition_confirmations')
    with op.batch_alter_table('signature_envelopes', schema=None) as batch_op:
        batch_op.drop_index('ix_signature_envelope_queue')

    op.drop_table('signature_envelopes')
    with op.batch_alter_table('seal_use_applications', schema=None) as batch_op:
        batch_op.drop_index('ix_seal_use_queue')

    op.drop_table('seal_use_applications')
    with op.batch_alter_table('record_integrity_events', schema=None) as batch_op:
        batch_op.drop_index('ix_record_integrity_timeline')

    op.drop_table('record_integrity_events')
    with op.batch_alter_table('record_dispositions', schema=None) as batch_op:
        batch_op.drop_index('uk_record_disposition_open', postgresql_where=sa.text("status IN ('PENDING_APPROVAL','APPROVED','CONFIRMING')"), sqlite_where=sa.text("status IN ('PENDING_APPROVAL','APPROVED','CONFIRMING')"))

    op.drop_table('record_dispositions')
    with op.batch_alter_table('record_access_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_record_access_queue')

    op.drop_table('record_access_requests')
    with op.batch_alter_table('record_revisions', schema=None) as batch_op:
        batch_op.drop_index('ix_record_revision_record')

    op.drop_table('record_revisions')
    with op.batch_alter_table('record_holds', schema=None) as batch_op:
        batch_op.drop_index('uk_record_hold_active', postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))

    op.drop_table('record_holds')
    with op.batch_alter_table('seal_custody_events', schema=None) as batch_op:
        batch_op.drop_index('uk_seal_pending_transfer', postgresql_where=sa.text("event_type = 'TRANSFER_REQUESTED' AND status = 'PENDING'"), sqlite_where=sa.text("event_type = 'TRANSFER_REQUESTED' AND status = 'PENDING'"))
        batch_op.drop_index('ix_seal_custody_timeline')

    op.drop_table('seal_custody_events')
    with op.batch_alter_table('record_files', schema=None) as batch_op:
        batch_op.drop_index('ix_record_file_retention')
        batch_op.drop_index('ix_record_file_catalog')

    op.drop_table('record_files')
    with op.batch_alter_table('seal_assets', schema=None) as batch_op:
        batch_op.drop_index('ix_seal_asset_catalog')

    op.drop_table('seal_assets')
    op.drop_table('record_categories')
    op.drop_table('signature_providers')
    with op.batch_alter_table('lease_contract_documents', schema=None) as batch_op:
        batch_op.drop_constraint('ck_lease_document_signed_truth', type_='check')
    # ### end Alembic commands ###
