"""workforce scheduling attendance performance qualification

Revision ID: c5f02d8e9c87
Revises: b4ea2c7d8f86
Create Date: 2026-08-15 06:44:07.503448

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5f02d8e9c87"
down_revision: str | None = "b4ea2c7d8f86"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workforce_qualification_types",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("validity_months", sa.Integer(), nullable=True),
        sa.Column("reminder_days", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('ACTIVE','RETIRED')", name="ck_workforce_qualification_type_status"
        ),
        sa.CheckConstraint(
            "reminder_days BETWEEN 0 AND 3650", name="ck_workforce_qualification_type_reminder"
        ),
        sa.CheckConstraint(
            "validity_months IS NULL OR validity_months > 0",
            name="ck_workforce_qualification_type_validity",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", name="uk_workforce_qualification_type_code"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_workforce_qualification_type_tenant_id"),
    )
    op.create_table(
        "workforce_attendance_locations",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("config_ref", sa.String(length=128), nullable=False),
        sa.Column("radius_m", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('ACTIVE','RETIRED')", name="ck_workforce_attendance_location_status"
        ),
        sa.CheckConstraint(
            "radius_m BETWEEN 10 AND 5000", name="ck_workforce_attendance_location_radius"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id"],
            ["parks.tenant_id", "parks.id"],
            name="fk_workforce_attendance_location_park",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_workforce_attendance_location_tenant_id"),
        sa.UniqueConstraint(
            "tenant_id", "park_id", "code", name="uk_workforce_attendance_location_code"
        ),
    )
    op.create_table(
        "workforce_attendance_policies",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("geofence_radius_m", sa.Integer(), nullable=False),
        sa.Column("allow_manual", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('ACTIVE','RETIRED')", name="ck_workforce_attendance_policy_status"
        ),
        sa.CheckConstraint(
            "geofence_radius_m BETWEEN 10 AND 5000", name="ck_workforce_attendance_radius"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id"],
            ["parks.tenant_id", "parks.id"],
            name="fk_workforce_attendance_policy_park",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_workforce_attendance_policy_tenant_id"),
        sa.UniqueConstraint(
            "tenant_id", "park_id", "code", name="uk_workforce_attendance_policy_code"
        ),
    )
    op.create_table(
        "workforce_employees",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("employee_no", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("department_name", sa.String(length=128), nullable=True),
        sa.Column("position_name", sa.String(length=128), nullable=True),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("mobile_masked", sa.String(length=16), nullable=True),
        sa.Column("mobile_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("identity_masked", sa.String(length=16), nullable=True),
        sa.Column("identity_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('ACTIVE','SUSPENDED','LEFT')", name="ck_workforce_employee_status"
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR end_date >= start_date", name="ck_workforce_employee_dates"
        ),
        sa.CheckConstraint("lock_version > 0", name="ck_workforce_employee_lock"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id"],
            ["parks.tenant_id", "parks.id"],
            name="fk_workforce_employee_park",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "user_id"],
            ["users.tenant_id", "users.id"],
            name="fk_workforce_employee_user",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "employee_no", name="uk_workforce_employee_no"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_workforce_employee_tenant_id"),
    )
    with op.batch_alter_table("workforce_employees", schema=None) as batch_op:
        batch_op.create_index(
            "ix_workforce_employee_scope", ["tenant_id", "park_id", "status"], unique=False
        )
        batch_op.create_index(
            "uk_workforce_employee_active_user",
            ["tenant_id", "user_id"],
            unique=True,
            postgresql_where=sa.text("user_id IS NOT NULL AND status <> 'LEFT'"),
            sqlite_where=sa.text("user_id IS NOT NULL AND status <> 'LEFT'"),
        )

    op.create_table(
        "workforce_performance_cycles",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','ACTIVE','CLOSED')", name="ck_workforce_performance_cycle_status"
        ),
        sa.CheckConstraint("end_date >= start_date", name="ck_workforce_performance_cycle_dates"),
        sa.CheckConstraint("lock_version > 0", name="ck_workforce_performance_cycle_lock"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id"],
            ["parks.tenant_id", "parks.id"],
            name="fk_workforce_performance_cycle_park",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_workforce_performance_cycle_tenant_id"),
        sa.UniqueConstraint(
            "tenant_id", "park_id", "code", name="uk_workforce_performance_cycle_code"
        ),
    )
    op.create_table(
        "workforce_shift_templates",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('ACTIVE','RETIRED')", name="ck_workforce_shift_template_status"
        ),
        sa.CheckConstraint("lock_version > 0", name="ck_workforce_shift_template_lock"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id"],
            ["parks.tenant_id", "parks.id"],
            name="fk_workforce_shift_template_park",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_workforce_shift_template_tenant_id"),
        sa.UniqueConstraint(
            "tenant_id", "park_id", "code", name="uk_workforce_shift_template_code"
        ),
    )
    op.create_table(
        "workforce_attendance_punches",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "employee_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "location_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("punch_type", sa.String(length=8), nullable=False),
        sa.Column("punched_at", sa.DateTime(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("location_result", sa.String(length=16), nullable=False),
        sa.Column("distance_m", sa.Integer(), nullable=True),
        sa.Column("device_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "recorded_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint(
            "location_result IN ('INSIDE','OUTSIDE','NOT_CHECKED')",
            name="ck_workforce_punch_location_result",
        ),
        sa.CheckConstraint("punch_type IN ('IN','OUT')", name="ck_workforce_punch_type"),
        sa.CheckConstraint(
            "source IN ('MANUAL','DEVICE','MOBILE')", name="ck_workforce_punch_source"
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "employee_id"],
            ["workforce_employees.tenant_id", "workforce_employees.id"],
            name="fk_workforce_punch_employee",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "location_id"],
            ["workforce_attendance_locations.tenant_id", "workforce_attendance_locations.id"],
            name="fk_workforce_punch_location",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uk_workforce_punch_key"),
    )
    with op.batch_alter_table("workforce_attendance_punches", schema=None) as batch_op:
        batch_op.create_index(
            "ix_workforce_punch_day", ["tenant_id", "employee_id", "punched_at"], unique=False
        )

    op.create_table(
        "workforce_attendance_summaries",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "employee_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("work_date", sa.Date(), nullable=False),
        sa.Column("scheduled_minutes", sa.Integer(), nullable=False),
        sa.Column("worked_minutes", sa.Integer(), nullable=False),
        sa.Column("first_in_at", sa.DateTime(), nullable=True),
        sa.Column("last_out_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("anomaly_code", sa.String(length=64), nullable=True),
        sa.Column("adjustment_reason", sa.String(length=1000), nullable=True),
        sa.Column(
            "adjusted_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('NORMAL','LATE','EARLY','ABSENT','LEAVE','ANOMALY','ADJUSTED')",
            name="ck_workforce_attendance_summary_status",
        ),
        sa.CheckConstraint("lock_version > 0", name="ck_workforce_attendance_summary_lock"),
        sa.ForeignKeyConstraint(
            ["adjusted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "employee_id"],
            ["workforce_employees.tenant_id", "workforce_employees.id"],
            name="fk_workforce_attendance_summary_employee",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "employee_id", "work_date", name="uk_workforce_attendance_summary_day"
        ),
        sa.UniqueConstraint("tenant_id", "id", name="uk_workforce_attendance_summary_tenant_id"),
    )
    with op.batch_alter_table("workforce_attendance_summaries", schema=None) as batch_op:
        batch_op.create_index(
            "ix_workforce_attendance_summary_scope",
            ["tenant_id", "park_id", "work_date", "status"],
            unique=False,
        )

    op.create_table(
        "workforce_employee_events",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "employee_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column(
            "actor_user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "employee_id"],
            ["workforce_employees.tenant_id", "workforce_employees.id"],
            name="fk_workforce_employee_event_employee",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workforce_employee_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_workforce_employee_event_timeline",
            ["tenant_id", "employee_id", "occurred_at"],
            unique=False,
        )

    op.create_table(
        "workforce_employee_qualifications",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "employee_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "qualification_type_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "attachment_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("credential_masked", sa.String(length=16), nullable=False),
        sa.Column("credential_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("issuer", sa.String(length=255), nullable=False),
        sa.Column("effective_on", sa.Date(), nullable=False),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "verified_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column(
            "revoked_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("revoke_reason", sa.String(length=1000), nullable=True),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','VERIFIED','EXPIRED','REVOKED')",
            name="ck_workforce_employee_qualification_status",
        ),
        sa.CheckConstraint(
            "expires_on IS NULL OR expires_on >= effective_on",
            name="ck_workforce_employee_qualification_dates",
        ),
        sa.CheckConstraint("lock_version > 0", name="ck_workforce_employee_qualification_lock"),
        sa.ForeignKeyConstraint(
            ["revoked_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "attachment_id"],
            ["attachments.tenant_id", "attachments.id"],
            name="fk_workforce_employee_qualification_attachment",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "employee_id"],
            ["workforce_employees.tenant_id", "workforce_employees.id"],
            name="fk_workforce_employee_qualification_employee",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "qualification_type_id"],
            ["workforce_qualification_types.tenant_id", "workforce_qualification_types.id"],
            name="fk_workforce_employee_qualification_type",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "employee_id",
            "qualification_type_id",
            "credential_fingerprint",
            name="uk_workforce_employee_qualification_credential",
        ),
        sa.UniqueConstraint(
            "tenant_id", "id", name="uk_workforce_employee_qualification_tenant_id"
        ),
    )
    with op.batch_alter_table("workforce_employee_qualifications", schema=None) as batch_op:
        batch_op.create_index(
            "ix_workforce_qualification_expiry", ["tenant_id", "status", "expires_on"], unique=False
        )

    op.create_table(
        "workforce_performance_goals",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("cycle_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "employee_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("target_value", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','LOCKED')", name="ck_workforce_performance_goal_status"
        ),
        sa.CheckConstraint(
            "weight > 0 AND weight <= 100", name="ck_workforce_performance_goal_weight"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "cycle_id"],
            ["workforce_performance_cycles.tenant_id", "workforce_performance_cycles.id"],
            name="fk_workforce_performance_goal_cycle",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "employee_id"],
            ["workforce_employees.tenant_id", "workforce_employees.id"],
            name="fk_workforce_performance_goal_employee",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "cycle_id",
            "employee_id",
            "code",
            name="uk_workforce_performance_goal_code",
        ),
    )
    op.create_table(
        "workforce_performance_reviews",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("cycle_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "employee_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "employee_user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "reviewer_user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(length=2000), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(), nullable=True),
        sa.Column("acknowledgement", sa.String(length=1000), nullable=True),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','PUBLISHED','ACKNOWLEDGED')",
            name="ck_workforce_performance_review_status",
        ),
        sa.CheckConstraint("lock_version > 0", name="ck_workforce_performance_review_lock"),
        sa.CheckConstraint(
            "rating >= 0 AND rating <= 100", name="ck_workforce_performance_review_rating"
        ),
        sa.CheckConstraint(
            "reviewer_user_id <> employee_user_id OR employee_user_id IS NULL",
            name="ck_workforce_performance_review_no_self",
        ),
        sa.ForeignKeyConstraint(
            ["employee_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "cycle_id"],
            ["workforce_performance_cycles.tenant_id", "workforce_performance_cycles.id"],
            name="fk_workforce_performance_review_cycle",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "employee_id"],
            ["workforce_employees.tenant_id", "workforce_employees.id"],
            name="fk_workforce_performance_review_employee",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "cycle_id", "employee_id", name="uk_workforce_performance_review_subject"
        ),
        sa.UniqueConstraint("tenant_id", "id", name="uk_workforce_performance_review_tenant_id"),
    )
    op.create_table(
        "workforce_shift_template_versions",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "template_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("cross_day", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("break_minutes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("late_grace_minutes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("early_grace_minutes", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "published_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("break_minutes BETWEEN 0 AND 480", name="ck_workforce_shift_break"),
        sa.CheckConstraint("version_no > 0", name="ck_workforce_shift_version_no"),
        sa.ForeignKeyConstraint(
            ["published_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "template_id"],
            ["workforce_shift_templates.tenant_id", "workforce_shift_templates.id"],
            name="fk_workforce_shift_version_template",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_workforce_shift_version_tenant_id"),
        sa.UniqueConstraint(
            "tenant_id", "template_id", "version_no", name="uk_workforce_shift_version"
        ),
    )
    op.create_table(
        "workforce_qualification_events",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "qualification_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column(
            "actor_user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "qualification_id"],
            ["workforce_employee_qualifications.tenant_id", "workforce_employee_qualifications.id"],
            name="fk_workforce_qualification_event_credential",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workforce_qualification_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_workforce_qualification_event_timeline",
            ["tenant_id", "qualification_id", "occurred_at"],
            unique=False,
        )

    op.create_table(
        "workforce_shift_assignments",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "employee_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "shift_version_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("work_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "assigned_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('ACTIVE','CANCELLED')", name="ck_workforce_shift_assignment_status"
        ),
        sa.CheckConstraint("lock_version > 0", name="ck_workforce_shift_assignment_lock"),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "employee_id"],
            ["workforce_employees.tenant_id", "workforce_employees.id"],
            name="fk_workforce_shift_assignment_employee",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "shift_version_id"],
            ["workforce_shift_template_versions.tenant_id", "workforce_shift_template_versions.id"],
            name="fk_workforce_shift_assignment_version",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_workforce_shift_assignment_tenant_id"),
    )
    with op.batch_alter_table("workforce_shift_assignments", schema=None) as batch_op:
        batch_op.create_index(
            "ix_workforce_roster_scope", ["tenant_id", "park_id", "work_date"], unique=False
        )
        batch_op.create_index(
            "uk_workforce_shift_assignment_active",
            ["tenant_id", "employee_id", "work_date"],
            unique=True,
            postgresql_where=sa.text("status = 'ACTIVE'"),
            sqlite_where=sa.text("status = 'ACTIVE'"),
        )

    op.create_table(
        "workforce_leave_requests",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "employee_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("leave_type", sa.String(length=16), nullable=False),
        sa.Column("start_at", sa.DateTime(), nullable=False),
        sa.Column("end_at", sa.DateTime(), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "approval_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("request_key", sa.String(length=128), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "requested_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "leave_type IN ('ANNUAL','SICK','PERSONAL','MATERNITY','PATERNITY','OTHER')",
            name="ck_workforce_leave_type",
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','PENDING_APPROVAL','APPROVED','REJECTED','RETURNED','CANCELLED')",
            name="ck_workforce_leave_status",
        ),
        sa.CheckConstraint("end_at > start_at", name="ck_workforce_leave_dates"),
        sa.CheckConstraint("lock_version > 0", name="ck_workforce_leave_lock"),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approval_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "employee_id"],
            ["workforce_employees.tenant_id", "workforce_employees.id"],
            name="fk_workforce_leave_employee",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_workforce_leave_tenant_id"),
        sa.UniqueConstraint("tenant_id", "request_key", name="uk_workforce_leave_key"),
    )
    with op.batch_alter_table("workforce_leave_requests", schema=None) as batch_op:
        batch_op.create_index(
            "ix_workforce_leave_scope", ["tenant_id", "park_id", "status", "start_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workforce_leave_requests", schema=None) as batch_op:
        batch_op.drop_index("ix_workforce_leave_scope")

    op.drop_table("workforce_leave_requests")
    with op.batch_alter_table("workforce_shift_assignments", schema=None) as batch_op:
        batch_op.drop_index(
            "uk_workforce_shift_assignment_active",
            postgresql_where=sa.text("status = 'ACTIVE'"),
            sqlite_where=sa.text("status = 'ACTIVE'"),
        )
        batch_op.drop_index("ix_workforce_roster_scope")

    op.drop_table("workforce_shift_assignments")
    with op.batch_alter_table("workforce_qualification_events", schema=None) as batch_op:
        batch_op.drop_index("ix_workforce_qualification_event_timeline")

    op.drop_table("workforce_qualification_events")
    op.drop_table("workforce_shift_template_versions")
    op.drop_table("workforce_performance_reviews")
    op.drop_table("workforce_performance_goals")
    with op.batch_alter_table("workforce_employee_qualifications", schema=None) as batch_op:
        batch_op.drop_index("ix_workforce_qualification_expiry")

    op.drop_table("workforce_employee_qualifications")
    with op.batch_alter_table("workforce_employee_events", schema=None) as batch_op:
        batch_op.drop_index("ix_workforce_employee_event_timeline")

    op.drop_table("workforce_employee_events")
    with op.batch_alter_table("workforce_attendance_summaries", schema=None) as batch_op:
        batch_op.drop_index("ix_workforce_attendance_summary_scope")

    op.drop_table("workforce_attendance_summaries")
    with op.batch_alter_table("workforce_attendance_punches", schema=None) as batch_op:
        batch_op.drop_index("ix_workforce_punch_day")

    op.drop_table("workforce_attendance_punches")
    op.drop_table("workforce_shift_templates")
    op.drop_table("workforce_performance_cycles")
    with op.batch_alter_table("workforce_employees", schema=None) as batch_op:
        batch_op.drop_index(
            "uk_workforce_employee_active_user",
            postgresql_where=sa.text("user_id IS NOT NULL AND status <> 'LEFT'"),
            sqlite_where=sa.text("user_id IS NOT NULL AND status <> 'LEFT'"),
        )
        batch_op.drop_index("ix_workforce_employee_scope")

    op.drop_table("workforce_employees")
    op.drop_table("workforce_attendance_policies")
    op.drop_table("workforce_attendance_locations")
    op.drop_table("workforce_qualification_types")
    # ### end Alembic commands ###
