"""supply procurement inventory outsourcing

Revision ID: d6a13e9f0b98
Revises: c5f02d8e9c87
Create Date: 2026-08-15 08:16:16.877613

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6a13e9f0b98"
down_revision: str | None = "c5f02d8e9c87"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SUPPLY_PERMISSIONS = (
    ("supply:read", "查看供应商、采购、库存与外包"),
    ("supplier:manage", "管理供应商与园区服务范围"),
    ("supplier:credential", "管理供应商资质脱敏证据"),
    ("procurement:request", "发起采购申请"),
    ("procurement:approve", "同步采购审批结果"),
    ("procurement:order", "管理采购订单与确认"),
    ("inventory:manage", "管理物料、仓库与收货"),
    ("inventory:issue", "申请、发放和退还库存"),
    ("inventory:adjust", "盘点、调整和冲销库存"),
    ("outsourcing:manage", "管理外包服务订单与执行"),
    ("outsourcing:accept", "验收外包服务并评价供应商"),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supply_materials",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column(
            "reorder_point", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("status IN ('ACTIVE','RETIRED')", name="ck_supply_material_status"),
        sa.CheckConstraint("reorder_point >= 0", name="ck_supply_material_reorder"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", name="uk_supply_material_code"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_supply_material_tenant_id"),
    )
    with op.batch_alter_table("supply_materials", schema=None) as batch_op:
        batch_op.create_index(
            "ix_supply_material_category", ["tenant_id", "category", "status"], unique=False
        )

    op.create_table(
        "supply_suppliers",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("party_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('ACTIVE','SUSPENDED','RETIRED')", name="ck_supply_supplier_status"
        ),
        sa.CheckConstraint("lock_version > 0", name="ck_supply_supplier_lock"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "created_by"],
            ["users.tenant_id", "users.id"],
            name="fk_supply_supplier_creator",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "party_id"],
            ["parties.tenant_id", "parties.id"],
            name="fk_supply_supplier_party",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", name="uk_supply_supplier_code"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_supply_supplier_tenant_id"),
        sa.UniqueConstraint("tenant_id", "party_id", name="uk_supply_supplier_party"),
    )
    with op.batch_alter_table("supply_suppliers", schema=None) as batch_op:
        batch_op.create_index("ix_supply_supplier_status", ["tenant_id", "status"], unique=False)

    op.create_table(
        "supply_warehouses",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("status IN ('ACTIVE','RETIRED')", name="ck_supply_warehouse_status"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id"],
            ["parks.tenant_id", "parks.id"],
            name="fk_supply_warehouse_park",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "park_id", "code", name="uk_supply_warehouse_code"),
        sa.UniqueConstraint(
            "tenant_id", "park_id", "id", name="uk_supply_warehouse_tenant_park_id"
        ),
    )
    op.create_table(
        "supply_stock_balances",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "warehouse_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "material_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "on_hand_qty", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "reserved_qty", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("lock_version > 0", name="ck_supply_stock_balance_lock"),
        sa.CheckConstraint("on_hand_qty >= 0", name="ck_supply_stock_on_hand_nonnegative"),
        sa.CheckConstraint(
            "reserved_qty >= 0 AND reserved_qty <= on_hand_qty",
            name="ck_supply_stock_reserved_valid",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "material_id"],
            ["supply_materials.tenant_id", "supply_materials.id"],
            name="fk_supply_stock_balance_material",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id", "warehouse_id"],
            ["supply_warehouses.tenant_id", "supply_warehouses.park_id", "supply_warehouses.id"],
            name="fk_supply_stock_balance_warehouse",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_supply_stock_balance_tenant_id"),
        sa.UniqueConstraint(
            "tenant_id", "park_id", "warehouse_id", "material_id", name="uk_supply_stock_balance"
        ),
    )
    with op.batch_alter_table("supply_stock_balances", schema=None) as batch_op:
        batch_op.create_index(
            "ix_supply_stock_balance_scope", ["tenant_id", "park_id", "warehouse_id"], unique=False
        )

    op.create_table(
        "supply_supplier_evaluations",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "supplier_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column(
            "source_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(length=1000), nullable=True),
        sa.Column(
            "evaluated_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("evaluated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint("score BETWEEN 1 AND 5", name="ck_supply_supplier_evaluation_score"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "evaluated_by"],
            ["users.tenant_id", "users.id"],
            name="fk_supply_supplier_evaluation_user",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id"],
            ["parks.tenant_id", "parks.id"],
            name="fk_supply_supplier_evaluation_park",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "supplier_id"],
            ["supply_suppliers.tenant_id", "supply_suppliers.id"],
            name="fk_supply_supplier_evaluation_supplier",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("supply_supplier_evaluations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_supply_supplier_evaluation_timeline",
            ["tenant_id", "supplier_id", "evaluated_at"],
            unique=False,
        )

    op.create_table(
        "supply_supplier_park_scopes",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "supplier_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("service_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('ACTIVE','SUSPENDED','RETIRED')", name="ck_supply_supplier_scope_status"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id"],
            ["parks.tenant_id", "parks.id"],
            name="fk_supply_supplier_scope_park",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "supplier_id"],
            ["supply_suppliers.tenant_id", "supply_suppliers.id"],
            name="fk_supply_supplier_scope_supplier",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "supplier_id", "park_id", "service_type", name="uk_supply_supplier_scope"
        ),
    )
    with op.batch_alter_table("supply_supplier_park_scopes", schema=None) as batch_op:
        batch_op.create_index(
            "ix_supply_supplier_scope_park", ["tenant_id", "park_id", "status"], unique=False
        )

    op.create_table(
        "supply_supplier_qualifications",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "supplier_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("qualification_type", sa.String(length=64), nullable=False),
        sa.Column("credential_masked", sa.String(length=32), nullable=False),
        sa.Column("credential_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("issuer", sa.String(length=128), nullable=False),
        sa.Column("effective_on", sa.Date(), nullable=False),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "attachment_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('ACTIVE','EXPIRED','REVOKED')",
            name="ck_supply_supplier_qualification_status",
        ),
        sa.CheckConstraint(
            "expires_on IS NULL OR expires_on >= effective_on",
            name="ck_supply_supplier_qualification_dates",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "attachment_id"],
            ["attachments.tenant_id", "attachments.id"],
            name="fk_supply_supplier_qualification_attachment",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "supplier_id"],
            ["supply_suppliers.tenant_id", "supply_suppliers.id"],
            name="fk_supply_supplier_qualification_supplier",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "supplier_id",
            "qualification_type",
            "credential_fingerprint",
            name="uk_supply_supplier_qualification",
        ),
    )
    with op.batch_alter_table("supply_supplier_qualifications", schema=None) as batch_op:
        batch_op.create_index(
            "ix_supply_supplier_qualification_expiry",
            ["tenant_id", "expires_on", "status"],
            unique=False,
        )

    op.create_table(
        "supply_stock_movements",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "balance_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "warehouse_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "material_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("movement_type", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("reference_type", sa.String(length=32), nullable=False),
        sa.Column(
            "reference_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "reverses_movement_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "actor_user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint(
            "movement_type IN ('RECEIPT','ISSUE','RETURN','ADJUSTMENT','REVERSAL')",
            name="ck_supply_stock_movement_type",
        ),
        sa.CheckConstraint("quantity <> 0", name="ck_supply_stock_movement_quantity"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "actor_user_id"],
            ["users.tenant_id", "users.id"],
            name="fk_supply_stock_movement_actor",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "balance_id"],
            ["supply_stock_balances.tenant_id", "supply_stock_balances.id"],
            name="fk_supply_stock_movement_balance",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "reverses_movement_id"],
            ["supply_stock_movements.tenant_id", "supply_stock_movements.id"],
            name="fk_supply_stock_movement_reversal",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_supply_stock_movement_tenant_id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uk_supply_stock_movement_key"),
    )
    with op.batch_alter_table("supply_stock_movements", schema=None) as batch_op:
        batch_op.create_index(
            "ix_supply_stock_movement_timeline",
            ["tenant_id", "park_id", "balance_id", "occurred_at"],
            unique=False,
        )

    op.create_table(
        "supply_procurement_requisitions",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("request_no", sa.String(length=40), nullable=False),
        sa.Column("purpose", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "approval_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "requested_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','PENDING_APPROVAL','APPROVED','REJECTED','CANCELLED','ORDERED')",
            name="ck_supply_procurement_requisition_status",
        ),
        sa.CheckConstraint("lock_version > 0", name="ck_supply_procurement_requisition_lock"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "approval_id"],
            ["approval_requests.tenant_id", "approval_requests.id"],
            name="fk_supply_procurement_requisition_approval",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id"],
            ["parks.tenant_id", "parks.id"],
            name="fk_supply_procurement_requisition_park",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "requested_by"],
            ["users.tenant_id", "users.id"],
            name="fk_supply_procurement_requisition_requester",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_supply_procurement_requisition_tenant_id"),
        sa.UniqueConstraint(
            "tenant_id", "idempotency_key", name="uk_supply_procurement_requisition_key"
        ),
        sa.UniqueConstraint("tenant_id", "request_no", name="uk_supply_procurement_requisition_no"),
    )
    with op.batch_alter_table("supply_procurement_requisitions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_supply_procurement_requisition_scope",
            ["tenant_id", "park_id", "status"],
            unique=False,
        )

    op.create_table(
        "supply_stocktakes",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "warehouse_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("stocktake_no", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "approval_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "counted_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','PENDING_APPROVAL','APPROVED','POSTED','REJECTED','CANCELLED')",
            name="ck_supply_stocktake_status",
        ),
        sa.CheckConstraint("lock_version > 0", name="ck_supply_stocktake_lock"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "approval_id"],
            ["approval_requests.tenant_id", "approval_requests.id"],
            name="fk_supply_stocktake_approval",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "counted_by"],
            ["users.tenant_id", "users.id"],
            name="fk_supply_stocktake_counter",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id", "warehouse_id"],
            ["supply_warehouses.tenant_id", "supply_warehouses.park_id", "supply_warehouses.id"],
            name="fk_supply_stocktake_warehouse",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_supply_stocktake_tenant_id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uk_supply_stocktake_key"),
        sa.UniqueConstraint("tenant_id", "stocktake_no", name="uk_supply_stocktake_no"),
    )
    op.create_table(
        "supply_inventory_requisitions",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("request_no", sa.String(length=40), nullable=False),
        sa.Column("purpose", sa.String(length=500), nullable=False),
        sa.Column(
            "work_order_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "approval_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "requested_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','PENDING_APPROVAL','APPROVED','PARTIALLY_ISSUED','ISSUED','CANCELLED','REJECTED')",
            name="ck_supply_inventory_requisition_status",
        ),
        sa.CheckConstraint("lock_version > 0", name="ck_supply_inventory_requisition_lock"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "approval_id"],
            ["approval_requests.tenant_id", "approval_requests.id"],
            name="fk_supply_inventory_requisition_approval",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id", "work_order_id"],
            ["work_orders.tenant_id", "work_orders.park_id", "work_orders.id"],
            name="fk_supply_inventory_requisition_work_order",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id"],
            ["parks.tenant_id", "parks.id"],
            name="fk_supply_inventory_requisition_park",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "requested_by"],
            ["users.tenant_id", "users.id"],
            name="fk_supply_inventory_requisition_requester",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_supply_inventory_requisition_tenant_id"),
        sa.UniqueConstraint(
            "tenant_id", "idempotency_key", name="uk_supply_inventory_requisition_key"
        ),
        sa.UniqueConstraint("tenant_id", "request_no", name="uk_supply_inventory_requisition_no"),
    )
    with op.batch_alter_table("supply_inventory_requisitions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_supply_inventory_requisition_scope",
            ["tenant_id", "park_id", "status"],
            unique=False,
        )

    op.create_table(
        "supply_outsourcing_orders",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "supplier_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "work_order_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("order_no", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("deliverables_json", sa.JSON(), nullable=False),
        sa.Column("sla_due_at", sa.DateTime(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "approval_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("settlement_state", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "requested_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','PENDING_APPROVAL','APPROVED','IN_PROGRESS','WAITING_ACCEPTANCE','REWORK','ACCEPTED','REJECTED','CANCELLED')",
            name="ck_supply_outsourcing_order_status",
        ),
        sa.CheckConstraint("amount >= 0", name="ck_supply_outsourcing_order_amount"),
        sa.CheckConstraint("lock_version > 0", name="ck_supply_outsourcing_order_lock"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "approval_id"],
            ["approval_requests.tenant_id", "approval_requests.id"],
            name="fk_supply_outsourcing_order_approval",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id", "work_order_id"],
            ["work_orders.tenant_id", "work_orders.park_id", "work_orders.id"],
            name="fk_supply_outsourcing_order_work_order",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id"],
            ["parks.tenant_id", "parks.id"],
            name="fk_supply_outsourcing_order_park",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "requested_by"],
            ["users.tenant_id", "users.id"],
            name="fk_supply_outsourcing_order_requester",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "supplier_id"],
            ["supply_suppliers.tenant_id", "supply_suppliers.id"],
            name="fk_supply_outsourcing_order_supplier",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_supply_outsourcing_order_tenant_id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uk_supply_outsourcing_order_key"),
        sa.UniqueConstraint("tenant_id", "order_no", name="uk_supply_outsourcing_order_no"),
    )
    with op.batch_alter_table("supply_outsourcing_orders", schema=None) as batch_op:
        batch_op.create_index(
            "ix_supply_outsourcing_order_scope", ["tenant_id", "park_id", "status"], unique=False
        )

    op.create_table(
        "supply_procurement_requisition_lines",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "requisition_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column(
            "material_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "estimated_unit_price",
            sa.Numeric(precision=18, scale=4),
            server_default="0",
            nullable=False,
        ),
        sa.Column("purpose", sa.String(length=255), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint(
            "estimated_unit_price >= 0", name="ck_supply_procurement_requisition_line_price"
        ),
        sa.CheckConstraint("quantity > 0", name="ck_supply_procurement_requisition_line_qty"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "material_id"],
            ["supply_materials.tenant_id", "supply_materials.id"],
            name="fk_supply_procurement_requisition_line_material",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "requisition_id"],
            ["supply_procurement_requisitions.tenant_id", "supply_procurement_requisitions.id"],
            name="fk_supply_procurement_requisition_line_header",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "id", name="uk_supply_procurement_requisition_line_tenant_id"
        ),
        sa.UniqueConstraint(
            "tenant_id", "requisition_id", "line_no", name="uk_supply_procurement_requisition_line"
        ),
    )
    op.create_table(
        "supply_purchase_orders",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "requisition_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "supplier_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("order_no", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("truth_mode", sa.String(length=24), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "total_amount", sa.Numeric(precision=18, scale=2), server_default="0", nullable=False
        ),
        sa.Column("lock_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "ordered_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("acknowledged_at", sa.DateTime(), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('ISSUED','ACK_PENDING','ACKNOWLEDGED','PARTIALLY_RECEIVED','RECEIVED','REJECTED','CANCELLED')",
            name="ck_supply_purchase_order_status",
        ),
        sa.CheckConstraint(
            "truth_mode IN ('LOCAL','EXTERNAL_PENDING')", name="ck_supply_purchase_order_truth"
        ),
        sa.CheckConstraint("lock_version > 0", name="ck_supply_purchase_order_lock"),
        sa.CheckConstraint("total_amount >= 0", name="ck_supply_purchase_order_total"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "ordered_by"],
            ["users.tenant_id", "users.id"],
            name="fk_supply_purchase_order_buyer",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id"],
            ["parks.tenant_id", "parks.id"],
            name="fk_supply_purchase_order_park",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "requisition_id"],
            ["supply_procurement_requisitions.tenant_id", "supply_procurement_requisitions.id"],
            name="fk_supply_purchase_order_requisition",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "supplier_id"],
            ["supply_suppliers.tenant_id", "supply_suppliers.id"],
            name="fk_supply_purchase_order_supplier",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_supply_purchase_order_tenant_id"),
        sa.UniqueConstraint("tenant_id", "order_no", name="uk_supply_purchase_order_no"),
        sa.UniqueConstraint(
            "tenant_id", "requisition_id", name="uk_supply_purchase_order_requisition"
        ),
    )
    with op.batch_alter_table("supply_purchase_orders", schema=None) as batch_op:
        batch_op.create_index(
            "ix_supply_purchase_order_scope", ["tenant_id", "park_id", "status"], unique=False
        )

    op.create_table(
        "supply_stocktake_lines",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "stocktake_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "material_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("expected_qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("counted_qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "adjustment_movement_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint(
            "expected_qty >= 0 AND counted_qty >= 0", name="ck_supply_stocktake_line_qty"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "adjustment_movement_id"],
            ["supply_stock_movements.tenant_id", "supply_stock_movements.id"],
            name="fk_supply_stocktake_line_movement",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "material_id"],
            ["supply_materials.tenant_id", "supply_materials.id"],
            name="fk_supply_stocktake_line_material",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "stocktake_id"],
            ["supply_stocktakes.tenant_id", "supply_stocktakes.id"],
            name="fk_supply_stocktake_line_header",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "stocktake_id", "material_id", name="uk_supply_stocktake_line"
        ),
    )
    op.create_table(
        "supply_goods_receipts",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("order_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "warehouse_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("receipt_no", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "received_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('POSTED','REVERSED')", name="ck_supply_goods_receipt_status"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "order_id"],
            ["supply_purchase_orders.tenant_id", "supply_purchase_orders.id"],
            name="fk_supply_goods_receipt_order",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id", "warehouse_id"],
            ["supply_warehouses.tenant_id", "supply_warehouses.park_id", "supply_warehouses.id"],
            name="fk_supply_goods_receipt_warehouse",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "received_by"],
            ["users.tenant_id", "users.id"],
            name="fk_supply_goods_receipt_receiver",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_supply_goods_receipt_tenant_id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uk_supply_goods_receipt_key"),
        sa.UniqueConstraint("tenant_id", "receipt_no", name="uk_supply_goods_receipt_no"),
    )
    op.create_table(
        "supply_inventory_requisition_lines",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "requisition_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column(
            "warehouse_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "material_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("requested_qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "reserved_qty", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "issued_qty", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "returned_qty", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint("requested_qty > 0", name="ck_supply_inventory_requisition_line_qty"),
        sa.CheckConstraint(
            "reserved_qty <= requested_qty AND issued_qty <= requested_qty AND returned_qty <= issued_qty",
            name="ck_supply_inventory_requisition_line_bounds",
        ),
        sa.CheckConstraint(
            "reserved_qty >= 0 AND issued_qty >= 0 AND returned_qty >= 0",
            name="ck_supply_inventory_requisition_line_progress",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "material_id"],
            ["supply_materials.tenant_id", "supply_materials.id"],
            name="fk_supply_inventory_requisition_line_material",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id", "warehouse_id"],
            ["supply_warehouses.tenant_id", "supply_warehouses.park_id", "supply_warehouses.id"],
            name="fk_supply_inventory_requisition_line_warehouse",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "requisition_id"],
            ["supply_inventory_requisitions.tenant_id", "supply_inventory_requisitions.id"],
            name="fk_supply_inventory_requisition_line_header",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "id", name="uk_supply_inventory_requisition_line_tenant_id"
        ),
        sa.UniqueConstraint(
            "tenant_id", "requisition_id", "line_no", name="uk_supply_inventory_requisition_line"
        ),
    )
    op.create_table(
        "supply_outsourcing_events",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("order_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("event_type", sa.String(length=24), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("evidence_json", sa.JSON(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column(
            "actor_user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('SUBMITTED','APPROVED','STARTED','PROGRESS','COMPLETED','ACCEPTED','REWORK','CANCELLED')",
            name="ck_supply_outsourcing_event_type",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "actor_user_id"],
            ["users.tenant_id", "users.id"],
            name="fk_supply_outsourcing_event_actor",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "order_id"],
            ["supply_outsourcing_orders.tenant_id", "supply_outsourcing_orders.id"],
            name="fk_supply_outsourcing_event_order",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uk_supply_outsourcing_event_key"),
    )
    with op.batch_alter_table("supply_outsourcing_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_supply_outsourcing_event_timeline",
            ["tenant_id", "order_id", "occurred_at"],
            unique=False,
        )

    op.create_table(
        "supply_purchase_order_lines",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("order_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "requisition_line_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column(
            "material_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("ordered_qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "received_qty", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint("ordered_qty > 0", name="ck_supply_purchase_order_line_qty"),
        sa.CheckConstraint(
            "received_qty >= 0 AND received_qty <= ordered_qty",
            name="ck_supply_purchase_order_line_received",
        ),
        sa.CheckConstraint("unit_price >= 0", name="ck_supply_purchase_order_line_price"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "material_id"],
            ["supply_materials.tenant_id", "supply_materials.id"],
            name="fk_supply_purchase_order_line_material",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "order_id"],
            ["supply_purchase_orders.tenant_id", "supply_purchase_orders.id"],
            name="fk_supply_purchase_order_line_header",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "requisition_line_id"],
            [
                "supply_procurement_requisition_lines.tenant_id",
                "supply_procurement_requisition_lines.id",
            ],
            name="fk_supply_purchase_order_line_request",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_supply_purchase_order_line_tenant_id"),
        sa.UniqueConstraint(
            "tenant_id", "order_id", "line_no", name="uk_supply_purchase_order_line"
        ),
    )
    op.create_table(
        "supply_goods_receipt_lines",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "receipt_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "order_line_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("batch_no", sa.String(length=64), nullable=True),
        sa.Column(
            "movement_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name="ck_supply_goods_receipt_line_qty"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "movement_id"],
            ["supply_stock_movements.tenant_id", "supply_stock_movements.id"],
            name="fk_supply_goods_receipt_line_movement",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "order_line_id"],
            ["supply_purchase_order_lines.tenant_id", "supply_purchase_order_lines.id"],
            name="fk_supply_goods_receipt_line_order",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "receipt_id"],
            ["supply_goods_receipts.tenant_id", "supply_goods_receipts.id"],
            name="fk_supply_goods_receipt_line_header",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "receipt_id", "order_line_id", name="uk_supply_goods_receipt_line"
        ),
    )
    permission_table = sa.table(
        "permissions",
        sa.column("code", sa.String(128)),
        sa.column("name", sa.String(128)),
        sa.column("module", sa.String(64)),
    )
    op.bulk_insert(
        permission_table,
        [{"code": code, "name": name, "module": "supply"} for code, name in SUPPLY_PERMISSIONS],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    permission_table = sa.table("permissions", sa.column("code", sa.String(128)))
    op.execute(
        permission_table.delete().where(
            permission_table.c.code.in_([code for code, _ in SUPPLY_PERMISSIONS])
        )
    )
    op.drop_table("supply_goods_receipt_lines")
    op.drop_table("supply_purchase_order_lines")
    with op.batch_alter_table("supply_outsourcing_events", schema=None) as batch_op:
        batch_op.drop_index("ix_supply_outsourcing_event_timeline")

    op.drop_table("supply_outsourcing_events")
    op.drop_table("supply_inventory_requisition_lines")
    op.drop_table("supply_goods_receipts")
    op.drop_table("supply_stocktake_lines")
    with op.batch_alter_table("supply_purchase_orders", schema=None) as batch_op:
        batch_op.drop_index("ix_supply_purchase_order_scope")

    op.drop_table("supply_purchase_orders")
    op.drop_table("supply_procurement_requisition_lines")
    with op.batch_alter_table("supply_outsourcing_orders", schema=None) as batch_op:
        batch_op.drop_index("ix_supply_outsourcing_order_scope")

    op.drop_table("supply_outsourcing_orders")
    with op.batch_alter_table("supply_inventory_requisitions", schema=None) as batch_op:
        batch_op.drop_index("ix_supply_inventory_requisition_scope")

    op.drop_table("supply_inventory_requisitions")
    op.drop_table("supply_stocktakes")
    with op.batch_alter_table("supply_procurement_requisitions", schema=None) as batch_op:
        batch_op.drop_index("ix_supply_procurement_requisition_scope")

    op.drop_table("supply_procurement_requisitions")
    with op.batch_alter_table("supply_stock_movements", schema=None) as batch_op:
        batch_op.drop_index("ix_supply_stock_movement_timeline")

    op.drop_table("supply_stock_movements")
    with op.batch_alter_table("supply_supplier_qualifications", schema=None) as batch_op:
        batch_op.drop_index("ix_supply_supplier_qualification_expiry")

    op.drop_table("supply_supplier_qualifications")
    with op.batch_alter_table("supply_supplier_park_scopes", schema=None) as batch_op:
        batch_op.drop_index("ix_supply_supplier_scope_park")

    op.drop_table("supply_supplier_park_scopes")
    with op.batch_alter_table("supply_supplier_evaluations", schema=None) as batch_op:
        batch_op.drop_index("ix_supply_supplier_evaluation_timeline")

    op.drop_table("supply_supplier_evaluations")
    with op.batch_alter_table("supply_stock_balances", schema=None) as batch_op:
        batch_op.drop_index("ix_supply_stock_balance_scope")

    op.drop_table("supply_stock_balances")
    op.drop_table("supply_warehouses")
    with op.batch_alter_table("supply_suppliers", schema=None) as batch_op:
        batch_op.drop_index("ix_supply_supplier_status")

    op.drop_table("supply_suppliers")
    with op.batch_alter_table("supply_materials", schema=None) as batch_op:
        batch_op.drop_index("ix_supply_material_category")

    op.drop_table("supply_materials")
    # ### end Alembic commands ###
