"""facility device inspection iot lifecycle

Revision ID: z2c80e5f6a64
Revises: y1b79d4e6f53
Create Date: 2026-08-15 03:04:03.411375

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "z2c80e5f6a64"
down_revision: Union[str, None] = "y1b79d4e6f53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The composite unit key must exist before facility_devices references it.
    with op.batch_alter_table("units", schema=None) as batch_op:
        batch_op.create_unique_constraint("uk_units_tenant_park_id", ["tenant_id", "park_id", "id"])

    op.create_table(
        "iot_providers",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("adapter_kind", sa.String(length=16), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("credential_ref", sa.String(length=128), nullable=True),
        sa.Column("severity_mapping_json", sa.JSON(), nullable=False),
        sa.Column("correlation_minutes", sa.Integer(), nullable=False),
        sa.Column("last_health_at", sa.DateTime(), nullable=True),
        sa.Column("last_health_code", sa.String(length=64), nullable=True),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "adapter_kind IN ('LOCAL','SANDBOX','HTTP')", name="ck_iot_provider_adapter_kind"
        ),
        sa.CheckConstraint(
            "status IN ('NOT_CONNECTED','SANDBOX','CONNECTED','DEGRADED')",
            name="ck_iot_provider_status",
        ),
        sa.CheckConstraint(
            "correlation_minutes > 0 AND correlation_minutes <= 10080",
            name="ck_iot_provider_correlation_minutes",
        ),
        sa.CheckConstraint("lock_version > 0", name="ck_iot_provider_lock_version"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", name="uk_iot_provider_code"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_iot_providers_tenant_id_id"),
    )
    op.create_table(
        "inspection_templates",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("device_type", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("status IN ('ACTIVE','RETIRED')", name="ck_inspection_template_status"),
        sa.CheckConstraint("current_version >= 0", name="ck_inspection_template_current_version"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", name="uk_inspection_template_code"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_inspection_templates_tenant_id_id"),
    )
    op.create_table(
        "inspection_template_versions",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "template_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "published_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column(
            "retired_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("retired_at", sa.DateTime(), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','PUBLISHED','RETIRED')",
            name="ck_inspection_template_version_status",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["published_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["retired_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "template_id"],
            ["inspection_templates.tenant_id", "inspection_templates.id"],
            name="fk_inspection_template_version_template",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_inspection_template_versions_tenant_id_id"),
        sa.UniqueConstraint(
            "tenant_id", "template_id", "version_no", name="uk_inspection_template_version"
        ),
    )
    with op.batch_alter_table("inspection_template_versions", schema=None) as batch_op:
        batch_op.create_index(
            "uk_inspection_template_published",
            ["tenant_id", "template_id"],
            unique=True,
            postgresql_where=sa.text("status = 'PUBLISHED'"),
            sqlite_where=sa.text("status = 'PUBLISHED'"),
        )

    op.create_table(
        "inspection_template_items",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "template_version_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("item_code", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("result_type", sa.String(length=16), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("critical", sa.Boolean(), nullable=False),
        sa.Column("minimum", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("maximum", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("options_json", sa.JSON(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint(
            "result_type IN ('BOOLEAN','NUMBER','TEXT','SELECT')",
            name="ck_inspection_item_result_type",
        ),
        sa.CheckConstraint("position > 0", name="ck_inspection_item_position"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "template_version_id"],
            ["inspection_template_versions.tenant_id", "inspection_template_versions.id"],
            name="fk_inspection_item_version",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "template_version_id", "item_code", name="uk_inspection_item_code"
        ),
        sa.UniqueConstraint(
            "tenant_id", "template_version_id", "position", name="uk_inspection_item_position"
        ),
    )
    op.create_table(
        "facility_devices",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("unit_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("device_code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("device_type", sa.String(length=32), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=False),
        sa.Column("criticality", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("manufacturer", sa.String(length=128), nullable=True),
        sa.Column("model_no", sa.String(length=128), nullable=True),
        sa.Column("serial_no", sa.String(length=128), nullable=True),
        sa.Column("commissioned_on", sa.DateTime(), nullable=True),
        sa.Column("warranty_expires_on", sa.DateTime(), nullable=True),
        sa.Column("properties_json", sa.JSON(), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("retired_at", sa.DateTime(), nullable=True),
        sa.Column(
            "retired_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("retirement_reason", sa.String(length=1000), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "criticality IN ('LOW','MEDIUM','HIGH','CRITICAL')",
            name="ck_facility_device_criticality",
        ),
        sa.CheckConstraint(
            "device_type IN ('FIRE','ELEVATOR','TRANSFORMER','ELECTRICAL','HVAC','WATER','SECURITY','CUSTOM')",
            name="ck_facility_device_type",
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','MAINTENANCE','RETIRED')", name="ck_facility_device_status"
        ),
        sa.CheckConstraint("lock_version > 0", name="ck_facility_device_lock_version"),
        sa.ForeignKeyConstraint(
            ["park_id"],
            ["parks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["retired_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id", "unit_id"],
            ["units.tenant_id", "units.park_id", "units.id"],
            name="fk_facility_device_unit",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id"],
            ["parks.tenant_id", "parks.id"],
            name="fk_facility_device_park",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "device_code", name="uk_facility_device_code"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_facility_devices_tenant_id_id"),
        sa.UniqueConstraint(
            "tenant_id", "park_id", "id", name="uk_facility_devices_tenant_park_id"
        ),
    )
    with op.batch_alter_table("facility_devices", schema=None) as batch_op:
        batch_op.create_index(
            "ix_facility_device_queue",
            ["tenant_id", "park_id", "status", "device_type"],
            unique=False,
        )

    op.create_table(
        "facility_device_history",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "device_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("before_json", sa.JSON(), nullable=True),
        sa.Column("after_json", sa.JSON(), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column(
            "changed_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("changed_at", sa.DateTime(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["park_id"],
            ["parks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id", "device_id"],
            ["facility_devices.tenant_id", "facility_devices.park_id", "facility_devices.id"],
            name="fk_facility_device_history_device",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "device_id", "version_no", name="uk_facility_device_history_version"
        ),
    )
    with op.batch_alter_table("facility_device_history", schema=None) as batch_op:
        batch_op.create_index(
            "ix_facility_device_history_timeline",
            ["tenant_id", "device_id", "changed_at"],
            unique=False,
        )

    op.create_table(
        "inspection_schedules",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "device_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "template_version_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "assignee_user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("local_due_time", sa.String(length=5), nullable=False),
        sa.Column("completion_window_minutes", sa.Integer(), nullable=False),
        sa.Column("missed_work_order", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("retired_at", sa.DateTime(), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('ACTIVE','PAUSED','RETIRED')", name="ck_inspection_schedule_status"
        ),
        sa.CheckConstraint(
            "completion_window_minutes > 0 AND completion_window_minutes <= 10080",
            name="ck_inspection_schedule_window",
        ),
        sa.CheckConstraint("lock_version > 0", name="ck_inspection_schedule_lock_version"),
        sa.CheckConstraint("weekday >= 1 AND weekday <= 7", name="ck_inspection_schedule_weekday"),
        sa.ForeignKeyConstraint(
            ["assignee_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["park_id"],
            ["parks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "assignee_user_id"],
            ["users.tenant_id", "users.id"],
            name="fk_inspection_schedule_assignee",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id", "device_id"],
            ["facility_devices.tenant_id", "facility_devices.park_id", "facility_devices.id"],
            name="fk_inspection_schedule_device",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "template_version_id"],
            ["inspection_template_versions.tenant_id", "inspection_template_versions.id"],
            name="fk_inspection_schedule_template_version",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", name="uk_inspection_schedule_code"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_inspection_schedules_tenant_id_id"),
        sa.UniqueConstraint(
            "tenant_id", "park_id", "id", name="uk_inspection_schedules_tenant_park_id"
        ),
    )
    with op.batch_alter_table("inspection_schedules", schema=None) as batch_op:
        batch_op.create_index(
            "ix_inspection_schedule_generation", ["tenant_id", "status", "weekday"], unique=False
        )

    op.create_table(
        "iot_device_bindings",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "provider_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "device_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("external_device_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("activated_at", sa.DateTime(), nullable=False),
        sa.Column("retired_at", sa.DateTime(), nullable=True),
        sa.Column(
            "changed_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("change_reason", sa.String(length=1000), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("status IN ('ACTIVE','RETIRED')", name="ck_iot_binding_status"),
        sa.CheckConstraint("lock_version > 0", name="ck_iot_binding_lock_version"),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["park_id"],
            ["parks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id", "device_id"],
            ["facility_devices.tenant_id", "facility_devices.park_id", "facility_devices.id"],
            name="fk_iot_binding_device",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "provider_id"],
            ["iot_providers.tenant_id", "iot_providers.id"],
            name="fk_iot_binding_provider",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_iot_device_bindings_tenant_id_id"),
    )
    with op.batch_alter_table("iot_device_bindings", schema=None) as batch_op:
        batch_op.create_index(
            "uk_iot_binding_device_active",
            ["tenant_id", "provider_id", "device_id"],
            unique=True,
            postgresql_where=sa.text("status = 'ACTIVE'"),
            sqlite_where=sa.text("status = 'ACTIVE'"),
        )
        batch_op.create_index(
            "uk_iot_binding_external_active",
            ["tenant_id", "provider_id", "external_device_key"],
            unique=True,
            postgresql_where=sa.text("status = 'ACTIVE'"),
            sqlite_where=sa.text("status = 'ACTIVE'"),
        )

    op.create_table(
        "inspection_tasks",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "schedule_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "device_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "template_version_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("template_snapshot_json", sa.JSON(), nullable=False),
        sa.Column(
            "assignee_user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("window_start", sa.DateTime(), nullable=False),
        sa.Column("window_due_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column(
            "completed_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('PENDING','IN_PROGRESS','PASSED','FAILED','MISSED','CANCELLED')",
            name="ck_inspection_task_status",
        ),
        sa.CheckConstraint("lock_version > 0", name="ck_inspection_task_lock_version"),
        sa.CheckConstraint("window_due_at > window_start", name="ck_inspection_task_window_order"),
        sa.ForeignKeyConstraint(
            ["assignee_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["completed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["park_id"],
            ["parks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "assignee_user_id"],
            ["users.tenant_id", "users.id"],
            name="fk_inspection_task_assignee",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id", "device_id"],
            ["facility_devices.tenant_id", "facility_devices.park_id", "facility_devices.id"],
            name="fk_inspection_task_device",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id", "schedule_id"],
            [
                "inspection_schedules.tenant_id",
                "inspection_schedules.park_id",
                "inspection_schedules.id",
            ],
            name="fk_inspection_task_schedule",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "template_version_id"],
            ["inspection_template_versions.tenant_id", "inspection_template_versions.id"],
            name="fk_inspection_task_template_version",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_inspection_tasks_tenant_id_id"),
        sa.UniqueConstraint(
            "tenant_id", "park_id", "id", name="uk_inspection_tasks_tenant_park_id"
        ),
        sa.UniqueConstraint(
            "tenant_id", "schedule_id", "window_start", name="uk_inspection_task_window"
        ),
    )
    with op.batch_alter_table("inspection_tasks", schema=None) as batch_op:
        batch_op.create_index(
            "ix_inspection_task_queue",
            ["tenant_id", "park_id", "status", "window_due_at"],
            unique=False,
        )

    op.create_table(
        "iot_alarms",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "binding_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "device_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("alarm_type", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(), nullable=True),
        sa.Column(
            "acknowledged_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "work_order_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("resolution_reason", sa.String(length=1000), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "severity IN ('INFO','WARNING','HIGH','CRITICAL')", name="ck_iot_alarm_severity"
        ),
        sa.CheckConstraint(
            "status IN ('OPEN','ACKNOWLEDGED','RESOLVED','CLOSED')", name="ck_iot_alarm_status"
        ),
        sa.CheckConstraint("lock_version > 0", name="ck_iot_alarm_lock_version"),
        sa.CheckConstraint("occurrence_count > 0", name="ck_iot_alarm_occurrences"),
        sa.ForeignKeyConstraint(
            ["acknowledged_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["park_id"],
            ["parks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "binding_id"],
            ["iot_device_bindings.tenant_id", "iot_device_bindings.id"],
            name="fk_iot_alarm_binding",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id", "device_id"],
            ["facility_devices.tenant_id", "facility_devices.park_id", "facility_devices.id"],
            name="fk_iot_alarm_device",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id", "work_order_id"],
            ["work_orders.tenant_id", "work_orders.park_id", "work_orders.id"],
            name="fk_iot_alarm_work_order",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_iot_alarms_tenant_id_id"),
        sa.UniqueConstraint("tenant_id", "park_id", "id", name="uk_iot_alarms_tenant_park_id"),
    )
    with op.batch_alter_table("iot_alarms", schema=None) as batch_op:
        batch_op.create_index(
            "ix_iot_alarm_queue",
            ["tenant_id", "park_id", "status", "severity", "last_seen_at"],
            unique=False,
        )
        batch_op.create_index(
            "uk_iot_alarm_active_correlation",
            ["tenant_id", "binding_id", "alarm_type"],
            unique=True,
            postgresql_where=sa.text("status IN ('OPEN','ACKNOWLEDGED')"),
            sqlite_where=sa.text("status IN ('OPEN','ACKNOWLEDGED')"),
        )

    op.create_table(
        "iot_binding_history",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "binding_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("snapshot_json", sa.JSON(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column(
            "changed_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("changed_at", sa.DateTime(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "binding_id"],
            ["iot_device_bindings.tenant_id", "iot_device_bindings.id"],
            name="fk_iot_binding_history_binding",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "binding_id", "version_no", name="uk_iot_binding_history_version"
        ),
    )
    op.create_table(
        "inspection_exceptions",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("task_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("item_code", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.String(length=1000), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "work_order_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "promoted_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "severity IN ('INFO','WARNING','HIGH','CRITICAL')",
            name="ck_inspection_exception_severity",
        ),
        sa.CheckConstraint(
            "status IN ('OPEN','PROMOTED','RESOLVED')", name="ck_inspection_exception_status"
        ),
        sa.ForeignKeyConstraint(
            ["park_id"],
            ["parks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["promoted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id", "task_id"],
            ["inspection_tasks.tenant_id", "inspection_tasks.park_id", "inspection_tasks.id"],
            name="fk_inspection_exception_task",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id", "work_order_id"],
            ["work_orders.tenant_id", "work_orders.park_id", "work_orders.id"],
            name="fk_inspection_exception_work_order",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uk_inspection_exceptions_tenant_id_id"),
        sa.UniqueConstraint(
            "tenant_id", "task_id", "item_code", name="uk_inspection_exception_item"
        ),
    )
    with op.batch_alter_table("inspection_exceptions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_inspection_exception_queue",
            ["tenant_id", "park_id", "status", "created_at"],
            unique=False,
        )

    op.create_table(
        "inspection_results",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("task_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("item_code", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("result_type", sa.String(length=16), nullable=False),
        sa.Column("text_value", sa.String(length=1000), nullable=True),
        sa.Column("number_value", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("critical", sa.Boolean(), nullable=False),
        sa.Column("evidence_refs_json", sa.JSON(), nullable=False),
        sa.Column("remark", sa.String(length=1000), nullable=True),
        sa.Column(
            "recorded_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint(
            "result_type IN ('BOOLEAN','NUMBER','TEXT','SELECT')", name="ck_inspection_result_type"
        ),
        sa.CheckConstraint("length(item_code) > 0", name="ck_inspection_result_item_code"),
        sa.CheckConstraint("position > 0", name="ck_inspection_result_position"),
        sa.ForeignKeyConstraint(
            ["park_id"],
            ["parks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id", "task_id"],
            ["inspection_tasks.tenant_id", "inspection_tasks.park_id", "inspection_tasks.id"],
            name="fk_inspection_result_task",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "task_id", "item_code", name="uk_inspection_result_item"),
    )
    with op.batch_alter_table("inspection_results", schema=None) as batch_op:
        batch_op.create_index(
            "ix_inspection_result_task", ["tenant_id", "task_id", "position"], unique=False
        )

    op.create_table(
        "inspection_task_events",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("task_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=True),
        sa.Column("to_status", sa.String(length=16), nullable=True),
        sa.Column(
            "actor_user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("reason", sa.String(length=1000), nullable=True),
        sa.Column("detail_json", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["park_id"],
            ["parks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id", "task_id"],
            ["inspection_tasks.tenant_id", "inspection_tasks.park_id", "inspection_tasks.id"],
            name="fk_inspection_task_event_task",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uk_inspection_task_event_key"),
    )
    with op.batch_alter_table("inspection_task_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_inspection_task_event_timeline",
            ["tenant_id", "task_id", "occurred_at"],
            unique=False,
        )

    op.create_table(
        "iot_alarm_escalations",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("alarm_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column(
            "created_by", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.CheckConstraint("level >= 1 AND level <= 4", name="ck_iot_alarm_escalation_level"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["park_id"],
            ["parks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id", "alarm_id"],
            ["iot_alarms.tenant_id", "iot_alarms.park_id", "iot_alarms.id"],
            name="fk_iot_alarm_escalation_alarm",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "alarm_id", "level", name="uk_iot_alarm_escalation_level"),
    )
    op.create_table(
        "iot_alarm_events",
        sa.Column(
            "tenant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("park_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "provider_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "binding_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("alarm_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("source_event_id", sa.String(length=128), nullable=False),
        sa.Column("source_time", sa.DateTime(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("raw_severity", sa.String(length=64), nullable=False),
        sa.Column("canonical_severity", sa.String(length=16), nullable=False),
        sa.Column("alarm_type", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column("safe_payload_json", sa.JSON(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["park_id"],
            ["parks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "binding_id"],
            ["iot_device_bindings.tenant_id", "iot_device_bindings.id"],
            name="fk_iot_alarm_event_binding",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "park_id", "alarm_id"],
            ["iot_alarms.tenant_id", "iot_alarms.park_id", "iot_alarms.id"],
            name="fk_iot_alarm_event_alarm",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "provider_id"],
            ["iot_providers.tenant_id", "iot_providers.id"],
            name="fk_iot_alarm_event_provider",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "provider_id", "source_event_id", name="uk_iot_alarm_source_event"
        ),
    )
    with op.batch_alter_table("iot_alarm_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_iot_alarm_event_timeline", ["tenant_id", "alarm_id", "source_time"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("iot_alarm_events", schema=None) as batch_op:
        batch_op.drop_index("ix_iot_alarm_event_timeline")

    op.drop_table("iot_alarm_events")
    op.drop_table("iot_alarm_escalations")
    with op.batch_alter_table("inspection_task_events", schema=None) as batch_op:
        batch_op.drop_index("ix_inspection_task_event_timeline")

    op.drop_table("inspection_task_events")
    with op.batch_alter_table("inspection_results", schema=None) as batch_op:
        batch_op.drop_index("ix_inspection_result_task")

    op.drop_table("inspection_results")
    with op.batch_alter_table("inspection_exceptions", schema=None) as batch_op:
        batch_op.drop_index("ix_inspection_exception_queue")

    op.drop_table("inspection_exceptions")
    op.drop_table("iot_binding_history")
    with op.batch_alter_table("iot_alarms", schema=None) as batch_op:
        batch_op.drop_index(
            "uk_iot_alarm_active_correlation",
            postgresql_where=sa.text("status IN ('OPEN','ACKNOWLEDGED')"),
            sqlite_where=sa.text("status IN ('OPEN','ACKNOWLEDGED')"),
        )
        batch_op.drop_index("ix_iot_alarm_queue")

    op.drop_table("iot_alarms")
    with op.batch_alter_table("inspection_tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_inspection_task_queue")

    op.drop_table("inspection_tasks")
    with op.batch_alter_table("iot_device_bindings", schema=None) as batch_op:
        batch_op.drop_index(
            "uk_iot_binding_external_active",
            postgresql_where=sa.text("status = 'ACTIVE'"),
            sqlite_where=sa.text("status = 'ACTIVE'"),
        )
        batch_op.drop_index(
            "uk_iot_binding_device_active",
            postgresql_where=sa.text("status = 'ACTIVE'"),
            sqlite_where=sa.text("status = 'ACTIVE'"),
        )

    op.drop_table("iot_device_bindings")
    with op.batch_alter_table("inspection_schedules", schema=None) as batch_op:
        batch_op.drop_index("ix_inspection_schedule_generation")

    op.drop_table("inspection_schedules")
    with op.batch_alter_table("facility_device_history", schema=None) as batch_op:
        batch_op.drop_index("ix_facility_device_history_timeline")

    op.drop_table("facility_device_history")
    with op.batch_alter_table("facility_devices", schema=None) as batch_op:
        batch_op.drop_index("ix_facility_device_queue")

    op.drop_table("facility_devices")
    op.drop_table("inspection_template_items")
    with op.batch_alter_table("inspection_template_versions", schema=None) as batch_op:
        batch_op.drop_index(
            "uk_inspection_template_published",
            postgresql_where=sa.text("status = 'PUBLISHED'"),
            sqlite_where=sa.text("status = 'PUBLISHED'"),
        )

    op.drop_table("inspection_template_versions")
    op.drop_table("inspection_templates")
    op.drop_table("iot_providers")
    with op.batch_alter_table("units", schema=None) as batch_op:
        batch_op.drop_constraint("uk_units_tenant_park_id", type_="unique")

    # ### end Alembic commands ###
